Homework 2
golenev/niffler-st5 pull request #2
Opened 2024-05-01 08:53 UTC by golenev

2024-05-07 16:24 UTC, sashkir7 requested changes
Добрый вечер!
Необходимо внести ряд правок. Более детально - отписался в комментариях

2024-05-07 16:24 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/jupiter/extension/UserQueueExtension.java
> +    private static final Queue<Pair<NifflerUser, NifflerUser>> USER_PAIRS = new ConcurrentLinkedQueue<>();
Не очень удачная структура для хранения коллекции пользователей различных ролей
Посмотрите, например, в стору мапы, где ключ - тип пользователя, а значение - коллекция (например, list) самих пользователей

2024-05-07 16:24 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/jupiter/extension/UserQueueExtension.java
> +        USER_PAIRS.add(Pair.of(NifflerUser.NIFFLER_QWERTY, NifflerUser.NIFFLER_CHUCKNORRIS));
И тогда здесь будет наполнение ранее созданной мапы
Можно будет "докидывать" столько пользователей, сколько нужно. И не быть привязанным к числу 2 (pair). 
Также я бы рекомендовал создавать пользователей в явном виде, а не использовать static переменные NifflerUser.NIFFLER_QWERTY, NifflerUser.NIFFLER_DIMA и тд.

2024-05-07 16:24 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/jupiter/extension/UserQueueExtension.java
> +        context.getStore(NAMESPACE).put(context.getUniqueId(), userPairForTest);
А если у нас для теста вообще пользователи не нужны? 
А если необходимо обработать данные из BeforeEach-блока? Очень много чего не предусмотрено - необходимо переделать

2024-05-07 16:24 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/model/NifflerUser.java
> +    public static final NifflerUser NIFFLER_CHUCKNORRIS = new NifflerUser("chucknorris", "12345");
Выше написал - я бы советовал пользователей создавать в явном виде, а не выносить в static переменные. Если пользователей будет 100, то будет 100 static переменных? Далее в extension их можно будет создавать "динамически" (на ходу)

2024-05-07 16:24 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/pageObjects/FriendsPage.java
> +    }
Название метода - проверка приглашения
А по факту - мы выполняем ряд проверок, после чего - кликаем на отклонить. 
Клика не должно быть в данном методе - в его названии об этом ничего не заявлено

2024-05-07 16:24 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/pageObjects/FriendsPage.java
> +
Пустые строки можно удалить

2024-05-07 16:24 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/pageObjects/LoginPage.java
> +        loginBtn.shouldBe(visible).click();
Перед click делать проверку на visible не нужно
Она уже есть "под капотом"

2024-05-07 16:24 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/pageObjects/MainPage.java
> +        $(allPeopleHeaderBtn).shouldBe(visible).click();
Аналогично

2024-05-07 16:24 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/pageObjects/MainPage.java
> +        logoutBtn.shouldBe(visible).click();
Аналогично

2024-05-07 16:24 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/pageObjects/PeoplePage.java
> +                .shouldHave(size(2)
А почему их должно быть 2? А если будет 3?
Метод надо стараться делать универсальным, не заточенным под какой-то конкретный единственный тест

2024-05-07 16:24 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/test/TestIncomeOutcomeFriendsInvitation.java
> +public class TestIncomeOutcomeFriendsInvitation {
Обычно слово Test пишут в конце названия тестового класса

2024-05-07 16:24 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/test/TestIncomeOutcomeFriendsInvitation.java
> +    void testIncomeOutcomeFriendsInvitation1(Pair<NifflerUser, NifflerUser> pair1) {
Параметры нужно получать (прокидывать) через @User(тип пользователя)

2024-05-07 16:24 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/test/TestIncomeOutcomeFriendsInvitation.java
> +                .at(MainPage.class)
В прошлом PR писал, что мне не очень нравится подход с at()
Можно ведь просто вызывать нужный метод из нужного экземпляра класса (обращаться напрямую к нему), либо написать, чтобы метод одного page-object класса возвращал экземпляр другого page-object класса. По типу login() возвращал экземпляр MainPage-класса

2024-05-07 16:24 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/test/TestIncomeOutcomeFriendsInvitation.java
> +    void testIncomeOutcomeFriendsInvitation2(Pair<NifflerUser, NifflerUser> pair1) {
Еще раз - пользователи должны прокидываться по типу
`@User(selector = WITH_FRIENDS) UserJson userForTest`
Везде ниже - аналогично

2024-05-07 16:33 UTC, golenev commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/model/NifflerUser.java
> +    public static final NifflerUser NIFFLER_CHUCKNORRIS = new NifflerUser("chucknorris", "12345");
На лекции мы разбирали кейс, где пользователей мы ВЫНУЖДЕНЫ хранить где-то, потому что генерировать их на лету невозможно по каким-то причинам. А если бы было возможно, тот этот экстеншен бы не понадобился, можно было просто на каждый поток по пользователю создавать

2024-05-07 16:37 UTC, golenev commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/test/TestIncomeOutcomeFriendsInvitation.java
> +                .at(MainPage.class)
"чтобы метод одного page-object класса возвращал экземпляр другого page-object класса."

это же не универсальный подход, а если мне надо, чтобы метод мог возвращать экземпляры каждый раз разных классов, мне что писать несколько методов под разный return ? а это как раз универсальный подход, я могу через рефлексию налету определять какой класс мне возвращать

2024-05-07 16:38 UTC, golenev commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/test/TestIncomeOutcomeFriendsInvitation.java
> +public class TestIncomeOutcomeFriendsInvitation {
у junit5 есть встроенная регулярка, которая проверяет паттерн названия класса, если бы он был нарушен, статический анализатор мне бы показал ошибку

2024-05-07 16:40 UTC, golenev commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/jupiter/extension/UserQueueExtension.java
> +        context.getStore(NAMESPACE).put(context.getUniqueId(), userPairForTest);
если бы пользователи были ненужны, то была бы пара GUEST_USER, GUEST_USER у которых был бы гостевой токен

2024-05-07 16:45 UTC, golenev commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/jupiter/extension/UserQueueExtension.java
> +        USER_PAIRS.add(Pair.of(NifflerUser.NIFFLER_QWERTY, NifflerUser.NIFFLER_CHUCKNORRIS));
не очень понятно, в таком кейсе как правило константно не более двух ролей - 1. тот кто отправляет приглашение 2. тот кто получает его
третий явно лишний, если бы кейс подразумевал иное, то возможно было бы ну совсем другое решение

2024-05-07 16:49 UTC, golenev commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/pageObjects/LoginPage.java
> +        loginBtn.shouldBe(visible).click();
нет, это не так 
"Before clicking, waits until element gets interactable and enabled."
ожидания видимости по дефолту нет

2024-05-07 16:50 UTC, golenev commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/pageObjects/LoginPage.java
> +        loginBtn.shouldBe(visible).click();
![image](https://github.com/golenev/niffler-st5/assets/84588235/bcff4a7b-0222-4f5a-aaa0-a4b5596a6bd2)

2024-05-07 16:50 UTC, golenev commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/pageObjects/MainPage.java
> +        $(allPeopleHeaderBtn).shouldBe(visible).click();
нет, тоже не так

2024-05-07 16:50 UTC, golenev commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/pageObjects/MainPage.java
> +        logoutBtn.shouldBe(visible).click();
нет, тоже не так

2024-05-09 02:11 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/jupiter/extension/UserQueueExtension.java
> +        USER_PAIRS.add(Pair.of(NifflerUser.NIFFLER_QWERTY, NifflerUser.NIFFLER_CHUCKNORRIS));
Я больше говорю про универсальное решение, которое мы сможем применять в будущем и для совершенно иных тестов. То есть возможность создавать n-е кол-во пользователей различных типов

2024-05-09 02:12 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/jupiter/extension/UserQueueExtension.java
> +        context.getStore(NAMESPACE).put(context.getUniqueId(), userPairForTest);
Спорный момент. Когда пользователи не нужны - мне они не нужны)
Не гостевые, не какие-либо еще. Ну ок

2024-05-09 02:13 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/model/NifflerUser.java
> +    public static final NifflerUser NIFFLER_CHUCKNORRIS = new NifflerUser("chucknorris", "12345");
Да, совершенно верно.
В данный момент времени пользователей мы задаем заранее и используем именно их.
Про ДИНАМИЧЕСКОЕ создание пользователей - я имел ввиду, что далее по курсу будет применять именно такой подход (в след. лекциях)

2024-05-09 02:14 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/pageObjects/LoginPage.java
> +        loginBtn.shouldBe(visible).click();
<img width="730" alt="Screenshot 2024-05-09 at 11 10 28" src="https://github.com/golenev/niffler-st5/assets/67268810/b454f5b2-8db9-4484-bdf0-9e671f65c651">

2024-05-09 02:14 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/pageObjects/MainPage.java
> +        $(allPeopleHeaderBtn).shouldBe(visible).click();
Ага. Фото выше

2024-05-09 02:18 UTC, sashkir7 commented on niffler-e-2-e-tests/src/test/java/guru/qa/niffler/test/TestIncomeOutcomeFriendsInvitation.java
> +                .at(MainPage.class)
Если метод может возвращать разные страницы (например, страница авторизации при нажатии на "Войти" - может возвращать главную страницу (авторизация успешна) либо возвращать саму себя (авторизация ошибочка). В данном случае можно ничего не возвращать void. А след. метод вызывать у созданного экземпляра класса не через chain-цепочку.
С точки зрения работы кода - все идентично. Это лишь "синтаксический сахар" - писать так или иначе

2024-05-09 02:19 UTC, sashkir7 commented
Ответил на ранее оставленные комментарии.
Есть ощущение, что часть из них вы не принимаете - любое мнение всегда субъективно =)

Работу принял. Если будут какие-то изменения, пишите - посмотрю

2024-05-09 02:19 UTC, sashkir7 approved these changes

2024-06-16 14:44 UTC, merged